import { Poppins } from 'next/font/google';
// import './globals.css';

const inter = Inter({ subsets: ['latin'] });

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '700', '800'],
});

export const metadata = {
  title: 'Pizza King',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <main className="max-w-4xl mx-auto p-4">
          {/* <Header /> */}
          {children}
          {/* <Footer /> */}
        </main>
      </body>
    </html>
  );
}
